// figma: 221:122 Marquee
export function Marquee(_p = {}) {
  const props = _p;
  return (
    <div className={props.className} style={{
      width: 1440,
      height: 44,
      display: "flex",
      flexDirection: "row",
      position: "relative",
      ...props.style,
    }}>
      <div style={{
        position: "absolute",
        left: 0,
        top: 0,
        width: 1440,
        height: 44,
        overflow: "hidden",
        background: "linear-gradient(rgb(30,79,186) 0%, rgb(184,105,159) 50%, rgb(203,122,68) 100%)",
        display: "flex",
        flexDirection: "row",
        gap: 40,
        padding: "16px 0px 16px 0px",
        alignItems: "center",
      }}>
        <span style={{
          position: "absolute",
          left: 0,
          top: 16,
          width: 41,
          height: 12,
          fontFamily: "Bricolage Grotesque",
          fontWeight: 700,
          fontSize: 12,
          lineHeight: 1,
          letterSpacing: "0.100em",
          color: "rgb(255,255,255)",
        }}>Label</span>
        <span style={{
          position: "absolute",
          left: 81,
          top: 16,
          width: 3,
          height: 12,
          fontFamily: "Bricolage Grotesque",
          fontWeight: 700,
          fontSize: 12,
          lineHeight: 1,
          letterSpacing: "0.100em",
          color: "rgba(255,255,255,0.7)",
        }}>·</span>
        <span style={{
          position: "absolute",
          left: 124,
          top: 16,
          width: 42,
          height: 12,
          fontFamily: "Bricolage Grotesque",
          fontWeight: 700,
          fontSize: 12,
          lineHeight: 1,
          letterSpacing: "0.100em",
          color: "rgb(255,255,255)",
        }}>Label</span>
        <span style={{
          position: "absolute",
          left: 206,
          top: 16,
          width: 3,
          height: 12,
          fontFamily: "Bricolage Grotesque",
          fontWeight: 700,
          fontSize: 12,
          lineHeight: 1,
          letterSpacing: "0.100em",
          color: "rgba(255,255,255,0.7)",
        }}>·</span>
        <span style={{
          position: "absolute",
          left: 249,
          top: 16,
          width: 41,
          height: 12,
          fontFamily: "Bricolage Grotesque",
          fontWeight: 700,
          fontSize: 12,
          lineHeight: 1,
          letterSpacing: "0.100em",
          color: "rgb(255,255,255)",
        }}>Label</span>
        <span style={{
          position: "absolute",
          left: 330,
          top: 16,
          width: 3,
          height: 12,
          fontFamily: "Bricolage Grotesque",
          fontWeight: 700,
          fontSize: 12,
          lineHeight: 1,
          letterSpacing: "0.100em",
          color: "rgba(255,255,255,0.7)",
        }}>·</span>
        <span style={{
          position: "absolute",
          left: 373,
          top: 16,
          width: 42,
          height: 12,
          fontFamily: "Bricolage Grotesque",
          fontWeight: 700,
          fontSize: 12,
          lineHeight: 1,
          letterSpacing: "0.100em",
          color: "rgb(255,255,255)",
        }}>Label</span>
        <span style={{
          position: "absolute",
          left: 455,
          top: 16,
          width: 3,
          height: 12,
          fontFamily: "Bricolage Grotesque",
          fontWeight: 700,
          fontSize: 12,
          lineHeight: 1,
          letterSpacing: "0.100em",
          color: "rgba(255,255,255,0.7)",
        }}>·</span>
        <span style={{
          position: "absolute",
          left: 498,
          top: 16,
          width: 41,
          height: 12,
          fontFamily: "Bricolage Grotesque",
          fontWeight: 700,
          fontSize: 12,
          lineHeight: 1,
          letterSpacing: "0.100em",
          color: "rgb(255,255,255)",
        }}>Label</span>
        <span style={{
          position: "absolute",
          left: 579,
          top: 16,
          width: 3,
          height: 12,
          fontFamily: "Bricolage Grotesque",
          fontWeight: 700,
          fontSize: 12,
          lineHeight: 1,
          letterSpacing: "0.100em",
          color: "rgba(255,255,255,0.7)",
        }}>·</span>
        <span style={{
          position: "absolute",
          left: 622,
          top: 16,
          width: 42,
          height: 12,
          fontFamily: "Bricolage Grotesque",
          fontWeight: 700,
          fontSize: 12,
          lineHeight: 1,
          letterSpacing: "0.100em",
          color: "rgb(255,255,255)",
        }}>Label</span>
        <span style={{
          position: "absolute",
          left: 704,
          top: 16,
          width: 3,
          height: 12,
          fontFamily: "Bricolage Grotesque",
          fontWeight: 700,
          fontSize: 12,
          lineHeight: 1,
          letterSpacing: "0.100em",
          color: "rgba(255,255,255,0.7)",
        }}>·</span>
        <span style={{
          position: "absolute",
          left: 747,
          top: 16,
          width: 41,
          height: 12,
          fontFamily: "Bricolage Grotesque",
          fontWeight: 700,
          fontSize: 12,
          lineHeight: 1,
          letterSpacing: "0.100em",
          color: "rgb(255,255,255)",
        }}>Label</span>
        <span style={{
          position: "absolute",
          left: 828,
          top: 16,
          width: 3,
          height: 12,
          fontFamily: "Bricolage Grotesque",
          fontWeight: 700,
          fontSize: 12,
          lineHeight: 1,
          letterSpacing: "0.100em",
          color: "rgba(255,255,255,0.7)",
        }}>·</span>
        <span style={{
          position: "absolute",
          left: 871,
          top: 16,
          width: 42,
          height: 12,
          fontFamily: "Bricolage Grotesque",
          fontWeight: 700,
          fontSize: 12,
          lineHeight: 1,
          letterSpacing: "0.100em",
          color: "rgb(255,255,255)",
        }}>Label</span>
        <span style={{
          position: "absolute",
          left: 953,
          top: 16,
          width: 3,
          height: 12,
          fontFamily: "Bricolage Grotesque",
          fontWeight: 700,
          fontSize: 12,
          lineHeight: 1,
          letterSpacing: "0.100em",
          color: "rgba(255,255,255,0.7)",
        }}>·</span>
        <span style={{
          position: "absolute",
          left: 996,
          top: 16,
          width: 41,
          height: 12,
          fontFamily: "Bricolage Grotesque",
          fontWeight: 700,
          fontSize: 12,
          lineHeight: 1,
          letterSpacing: "0.100em",
          color: "rgb(255,255,255)",
        }}>Label</span>
        <span style={{
          position: "absolute",
          left: 1077,
          top: 16,
          width: 3,
          height: 12,
          fontFamily: "Bricolage Grotesque",
          fontWeight: 700,
          fontSize: 12,
          lineHeight: 1,
          letterSpacing: "0.100em",
          color: "rgba(255,255,255,0.7)",
        }}>·</span>
        <span style={{
          position: "absolute",
          left: 1120,
          top: 16,
          width: 42,
          height: 12,
          fontFamily: "Bricolage Grotesque",
          fontWeight: 700,
          fontSize: 12,
          lineHeight: 1,
          letterSpacing: "0.100em",
          color: "rgb(255,255,255)",
        }}>Label</span>
        <span style={{
          position: "absolute",
          left: 1202,
          top: 16,
          width: 3,
          height: 12,
          fontFamily: "Bricolage Grotesque",
          fontWeight: 700,
          fontSize: 12,
          lineHeight: 1,
          letterSpacing: "0.100em",
          color: "rgba(255,255,255,0.7)",
        }}>·</span>
        <span style={{
          position: "absolute",
          left: 1245,
          top: 16,
          width: 41,
          height: 12,
          fontFamily: "Bricolage Grotesque",
          fontWeight: 700,
          fontSize: 12,
          lineHeight: 1,
          letterSpacing: "0.100em",
          color: "rgb(255,255,255)",
        }}>Label</span>
        <span style={{
          position: "absolute",
          left: 1326,
          top: 16,
          width: 3,
          height: 12,
          fontFamily: "Bricolage Grotesque",
          fontWeight: 700,
          fontSize: 12,
          lineHeight: 1,
          letterSpacing: "0.100em",
          color: "rgba(255,255,255,0.7)",
        }}>·</span>
        <span style={{
          position: "absolute",
          left: 1369,
          top: 16,
          width: 42,
          height: 12,
          fontFamily: "Bricolage Grotesque",
          fontWeight: 700,
          fontSize: 12,
          lineHeight: 1,
          letterSpacing: "0.100em",
          color: "rgb(255,255,255)",
        }}>Label</span>
        <span style={{
          position: "absolute",
          left: 1451,
          top: 16,
          width: 3,
          height: 12,
          fontFamily: "Bricolage Grotesque",
          fontWeight: 700,
          fontSize: 12,
          lineHeight: 1,
          letterSpacing: "0.100em",
          color: "rgba(255,255,255,0.7)",
        }}>·</span>
      </div>
    </div>
  );
}
export default Marquee;
